# Generated by Django 4.0.4 on 2022-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_no', models.IntegerField(verbose_name='客户端号')),
                ('score', models.IntegerField(verbose_name='客户端用户分数')),
            ],
            options={
                'db_table': 'client_user_score',
            },
        ),
    ]
